# This workflow needs to be run on demand
# It will search for all repositories containing the provided
# action and open pull requests if necessary.

name: Update workflow from org template

on: workflow_dispatch

jobs:
  repositories:
    runs-on: ubuntu-latest

    outputs:
      repositories: ${{ steps.search-repos.outputs.matrix }}
      workflow: ${{ matrix.workflows.workflow }}

    strategy:
      fail-fast: false
      matrix:
        workflows: [
          { "file":"stylelint.config.js", "workflow":"lint-stylelint.yml" },
          { "file":".eslintrc.js", "workflow":"lint-eslint.yml" },
          { "file":".php-cs-fixer.dist.php", "workflow":"lint-php-cs.yml" },
          { "file":".php_cs.dist", "workflow":"lint-php-cs.yml" },
          { "file":"composer.json", "workflow":"lint-php.yml" }
        ]

    steps:
      - name: Search repositories using the ${{ github.event.inputs.name }} workflow
        id: search-repos
        # This is a simple curl to fetch the list of repos containing a file and extracting the repo names
        run: |
          REPOS=$(curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/search/code?q=org%3Anextcloud%20${{ matrix.workflows.search }}%20path%3A%2F%20filename%3A${{ matrix.workflows.file }}&per_page=100" | jq -c '.items | map(.repository.name) | unique')
          echo "::set-output name=matrix::$REPOS"

  dispatch:
    runs-on: ubuntu-latest
    needs: repositories

    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(needs.repositories.outputs.repositories) }}
        workflow: [ "${{ needs.repositories.outputs.workflow }}" ]
        
    steps:
      - run: echo ${{ matrix.workflow }} on ${{ matrix.repository }}
