# This workflow needs to be run on demand
# It will search for all repositories containing the provided
# action and open pull requests if necessary.

name: Update workflow from org template

on: workflow_dispatch

jobs:
  repositories:
    runs-on: ubuntu-latest

    outputs:
      repositories: ${{ steps.search-repos.outputs.matrix }}
      workflow: ${{ matrix.workflows.workflow }}

    strategy:
      fail-fast: false
      matrix:
        workflows: [
          { "file":"stylelint.config.js", "workflow":"lint-stylelint.yml" },
          { "file":".eslintrc.js", "workflow":"lint-eslint.yml" },
          { "file":".php-cs-fixer.dist.php", "workflow":"lint-php-cs.yml" },
          { "file":".php_cs.dist", "workflow":"lint-php-cs.yml" },
          { "file":"composer.json", "search": "cs:fix php-cs-fixer fix", "workflow":"lint-php.yml" }
        ]

    steps:
      - name: Search repositories using the ${{ github.event.inputs.name }} workflow
        id: search-repos
        # This is a simple curl to fetch the list of repos containing a file and extracting the repo names
        run: |
          REPOS=$(curl -G -H "Accept: application/vnd.github.v3+json" --data-urlencode "q=org:nextcloud ${{ matrix.workflows.search }} filename:${{ matrix.workflows.file }}" "https://api.github.com/search/code?per_page=100" | jq -c '.items | map(.repository.name) | unique')
          echo "::set-output name=${{ matrix.workflows.file }}::$REPOS"

  dispatch:
    runs-on: ubuntu-latest
    needs: repositories
    
    strategy:
      fail-fast: false
      matrix:
        workflows: ${{ fromJSON(needs) }}
        
    steps:
      - run: echo 1
